Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,6 +26,12 @@ jobs:
       - name: 📥 Checkout code
         uses: actions/checkout@v3
 
+      - name: 🐳 Build and Push Docker Image
+        run: |
+          echo "Building Docker image..."
+          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
+          docker build -t $DOCKER_USERNAME/drupal-custom:latest .
+          docker push $DOCKER_USERNAME/drupal-custom:latest
 
       - name: 🔐 Setup SSH Key
         run: |
@@ -48,10 +54,10 @@ jobs:
 
             echo "🔧 Mounting disk if not already..."
             if ! mountpoint -q /mnt/drupal-data; then
-              sudo mkfs.ext4 /dev/xvdf || echo "Already formatted"
+              sudo mkfs.ext4 /dev/nvme1n1 || echo "Already formatted"
               sudo mkdir -p /mnt/drupal-data/config /mnt/drupal-data/files
-              sudo mount /dev/xvdf /mnt/drupal-data
-              echo "/dev/xvdf /mnt/drupal-data ext4 defaults,nofail 0 2" | sudo tee -a /etc/fstab
+              sudo mount /dev/nvme1n1 /mnt/drupal-data
+              echo "/dev/nvme1n1 /mnt/drupal-data ext4 defaults,nofail 0 2" | sudo tee -a /etc/fstab
             fi
 
             echo "📁 Preparing folders and permissions..."
